# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
jobs:
  update_sheet:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Install jq
          command: sudo apt-get update && sudo apt-get install jq
      - run:
          name: Update Character Sheets
          command: |
              .circleci/update_sheets.sh
version: 2.1
# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  update_sheets:
    jobs:
      - update_sheet:
          context: char-sheet-app-staging
          filters:
            branches:
              only:
                - master